---
title: "PUBH 614 lecture notes and recordings"
output:
  html_document:
    highlight: pygments
    theme: default
    toc: false
    toc_float: true
vignette: >
  %\VignetteIndexEntry{Lecture notes and videos}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
engine: knitr
---

| Session    | YouTube                                                                 | PDF                                                                                                                                                                                                                             | PPT                                                                                                                                                                                                                                  |
|------------|-------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Session 1  | [Session 1 - 1](https://youtu.be/5JVm-OabjqM?si=diU_lDDTIsaODnUn)   | [Session 1 Notes](https://www.dropbox.com/scl/fi/jvyhs6w0bjkgt9nk4i0qm/PUBH614-session-1-notes-view.pdf?rlkey=8iytzoe9t4w4v72z4svxo96nl&st=vllees4j&dl=0)  | [Session 1 Slides](https://www.dropbox.com/scl/fi/jcx8lwcj0bykpruo9dcq3/PUBH614-session-1-complete-slide-set.pptx?rlkey=bb3g0bewywrc71bneck3o05v3&st=i7rkd0gl&dl=0) |
|            | [Session 1 - 2](https://youtu.be/F2PgR2Sd43U?si=weMh7-jKiF72fTPk)   |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 1 - 3](https://youtu.be/8yvG5BpOKuA?si=vdnwYJoTlbX2M9hP)   |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 1 - 4](https://youtu.be/mtZT7K_-V28?si=Gwgdc9A1qe6rQQo4)   |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 1 - 5](https://youtu.be/nXzHEwqEwaM?si=YsJ0oK9IjuEfyRoK)   |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            |                                                                         |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
| Session 2  | [Session 2 - 1](https://youtu.be/unEFEnS3ly0?si=Y1HAdyCbuwd3pCwO)   | [Session 2 Notes](https://www.dropbox.com/scl/fi/4te0wh87d6dwypfoobkfy/PUBH614-session-2-notes-view.pdf?rlkey=1fftq2zlyo9y2s5c47jyuavbx&st=ttg2a09g&dl=0)  | [Session 2 Slides](https://www.dropbox.com/scl/fi/cd6porq8q63cqrri11po4/PUBH614-session-2-complete-slide-set.pptx?rlkey=cjj5y0ntzkgtugap7145j5xde&st=kp7c7zss&dl=0) |
|            | [Session 2 - 2](https://youtu.be/d0rpK3Tc78o?si=ZnZ6ntAucOU0bUln)   |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 2 - 3](https://youtu.be/DxYEy3oonMM?si=WHFoGSE2Ebvv8Hv2)   |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            |                                                                         |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
| Session 3  | [Session 3 - 1](https://youtu.be/Bwb7SgZLKjk?si=2gThtOhhyWtaYfL-)   | [Session 3 Notes](https://www.dropbox.com/scl/fi/s9hbu38ga75pth4261xfc/PUBH614-session-3-notes-view.pdf?rlkey=2rvo3et39elx3f4uaiwipo0qn&st=m75w6p38&dl=0)  | [Session 3 Slides](https://www.dropbox.com/scl/fi/xzrxkjrwo7048joyyn5hs/PUBH614-session-3-complete-slide-set.pptx?rlkey=ihr2te6i6iinxkcz2hcccaf6s&st=mzfck6kx&dl=0) |
|            | [Session 3 - 2](https://youtu.be/SL9CPCWDdm0?si=7q04i8eldQi7OYy-)   |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 3 - 3](https://youtu.be/rcjDTUMPVLY?si=Aw6jvo3V4U2gTJBC) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 3 - 4](https://youtu.be/qvOCrDfqFnU?si=TFp-yZLBRi1Kmiad) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 3 - 5](https://youtu.be/ZcCuG5ixDnQ?si=QTu1XBHjIk9ePdnf) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            |                                                                         |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
| Session 4  | [Session 4 - 1](https://youtu.be/ahRlOh622UQ?si=7BVjRZ9LgwfZ-Rda) | [Session 4 Notes](https://www.dropbox.com/scl/fi/ghtwsk3rcmhz9ayf6xtzv/PUBH614-session-4-notes-view.pdf?rlkey=v8ltpkplpa0vvojk8o7h6qoaj&st=ylmgol6v&dl=0)  | [Session 4 Slides](https://www.dropbox.com/scl/fi/iitljuq0z0cbfii6t5q3y/PUBH614-session-4-complete-slide-set.pptx?rlkey=4elvx9d7kp30yzmgqunvhb23l&st=003g9vr6&dl=0) |
|            | [Session 4 - 2](https://youtu.be/bS2tIcJgXx0?si=gJqZATIEgH-Ed3A1) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 4 - 3](https://youtu.be/jpCV4hF--M8?si=--Pyd9aJsv2KmK8s) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 4 - 4](https://youtu.be/SGMsjSzAicM?si=by1_FP3mToRHY0Qr) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 4 - 5](https://youtu.be/7qBj-V7U684?si=-JyPifwxOJS9BxTO) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 4 - 6](https://youtu.be/hSb598D3teo?si=Lhn7iTlI0Z2Kzl8E) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            |                                                                         |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
| Session 5  | [Session 5 - 1](https://youtu.be/cwYJWk3mUW0?si=hxECVTHCAjBLQWKV) | [Session 5 Notes](https://www.dropbox.com/scl/fi/mwrkkcldv1u0mzh3wqbdx/PUBH614-session-5-notes-view.pdf?rlkey=zlv40avxgn0gmzn0pe039crgl&st=8igmaihg&dl=0)  | [Session 5 Slides](https://www.dropbox.com/scl/fi/dxszec4cvz0g12flcx94p/PUBH614-session-5-complete-slide-set.pptx?rlkey=lfb6bie19g29bjoo20jvm8jy9&st=qiciggtr&dl=0) |
|            | [Session 5 - 2](https://youtu.be/sjEIIfVWlQM?si=Px6GEZMQqgLDB6h2) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 5 - 3](https://youtu.be/587DakNKCA4?si=RR8BRda2-4DBk4xq) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 5 - 4](https://youtu.be/evBnKk6_H30?si=rO81EhccXK21mfOr) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 5 - 5](https://youtu.be/XULtYsIMUGM?si=_X-hkX8ubwI_Ceml) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            |                                                                         |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
| Session 6  | [Session 6 - 1](https://youtu.be/Bmnbhs58TUc?si=6SEZvm_aZ9jSYUIG) | [Session 6 Notes](https://www.dropbox.com/scl/fi/8fgm688sxfkcrzboie8hy/PUBH614-session-6-notes-view.pdf?rlkey=agkfvolek2cy41jtdv3dnzoy0&st=8mh0q0o1&dl=0)  | [Session 6 Slides](https://www.dropbox.com/scl/fi/7gkv8b9n2knqxswjj730a/PUBH614-session-6-complete-slide-set.pptx?rlkey=gafs8470wtv6lda4gavwi7kyv&st=2rcwhxe9&dl=0) |
|            | [Session 6 - 2](https://youtu.be/wm16K657y-E?si=x9RH4xdrMgvBMRUn) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 6 - 3](https://youtu.be/Gdt9PdWihPQ?si=XevWVwiVKxvSU538) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 6 - 4](https://youtu.be/FDGAvRByk30?si=qHa3yjLdTQkmjbes) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 6 - 5](https://youtu.be/Ygg398qmtkQ?si=UhFYzpyq-fWV5pKg) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 6 - 6](https://youtu.be/Btc3feRjEbQ?si=RHEsdW1nzt1T1agO) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 6 - 7](https://youtu.be/8l3kvQkdgYo?si=9QTwfvipoA6DAKJx) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            |                                                                         |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
| Session 7  | [Session 7 - 1](https://youtu.be/FQPAwZQyqtQ?si=ee-9CyJ7MAujYXf_) | [Session 7 Notes](https://www.dropbox.com/scl/fi/u8kyj1j0sqzbc72mfmoj1/PUBH614-session-7-notes-view.pdf?rlkey=w7bpte9vmeoe3hmzik1kqahf9&st=4jh32wk8&dl=0)  | [Session 7 Slides](https://www.dropbox.com/scl/fi/os13w8ix4hedkjqvokecf/PUBH614-session-7-complete-slide-set.pptx?rlkey=jcfnywy7acu035i1igdmjyonc&st=kg8nzfal&dl=0) |
|            | [Session 7 - 2](https://youtu.be/fXaLrPORMbs?si=cayJjbz62jF-IDiY) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 7 - 3](https://youtu.be/s7l1_QbvsoI?si=q-AaNT86cgSlfo7F) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 7 - 4](https://youtu.be/XvKoxWuNWNM?si=a_xoUbJOHvBSA5g2) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 7 - 5](https://youtu.be/DWV6oFSZA18?si=st_eFAbWXPle_bl3) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            |                                                                         |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
| Session 8  | [Session 8 - 1](https://youtu.be/8hkta9KO0G4?si=U5xSvKpnCjU1_kiD) | [Session 8 Notes](https://www.dropbox.com/scl/fi/re32ein2eecu4s93ogmrz/PUBH614-session-8-notes-view.pdf?rlkey=99f3xte50rihhp53orrzxzxpy&st=bpy8zjrc&dl=0)  | [Session 8 Slides](https://www.dropbox.com/scl/fi/44pnjjcmzycuw26hr9n4a/PUBH614-session-8-complete-slide-set.pptx?rlkey=dv5yunrd203hup6fh3q4g3lql&st=b7zk26kx&dl=0) |
|            | [Session 8 - 2](https://youtu.be/O9Vc3Zd8ssI?si=nnq4IL7sXQoWCXQQ) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 8 - 3](https://youtu.be/A0SBxc87yc0?si=4ewhCAzCWFSnyMq3) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 8 - 4](https://youtu.be/86WY-mf16uo?si=6UotviYbfi-gW0YP) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            | [Session 8 - 5](https://youtu.be/jGqg3-1nfnQ?si=j7G55RXZ-pQU5Etd) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            |                                                                         |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
| Session 9  | [Session 9 - 1](https://youtu.be/NZg5KR682rw?si=BT5W0lq_jGnVsRrO) | [Session 9 Notes](https://www.dropbox.com/scl/fi/hx8lf7wuqlvtg964w79tr/PUBH614-session-9-notes-view.pdf?rlkey=svdd44f0fcl2dg70ysqg7bp9l&st=f5sieg62&dl=0)  | [Session 9 Slides](https://www.dropbox.com/scl/fi/rc3jg07le6nt1yr44w6dr/PUBH614-session-9-complete-slide-set.pptx?rlkey=e4ofqz931wt7aghtkhzpg9iu8&st=1kcs31mq&dl=0) |
|            | [Session 9 - 2](https://youtu.be/rnvHcN7YTzM?si=iALc4Kvrjzhop50u) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
|            |                                                                         |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                      |
| Session 10 | [Session 10 - 1](https://youtu.be/taP3IyHoikE?si=isQ2r-wAjkJk9ivm) | [Session 10 Notes](https://www.dropbox.com/scl/fi/s8b82lhvub5ua0k19z6dw/PUBH614-session-10-notes-view.pdf?rlkey=koii5ehebgieohm5nl1mgcqam&st=4rgx2zgz&dl=0) |                                                                                                                                                                                                                                  |
|            | [Session 10 - 2](https://youtu.be/anHYiHiS6Ck?si=of-MfMdz3kGi9MwR) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                  |
|            | [Session 10 - 3](https://youtu.be/lL0KGrqJzeY?si=zBGu0wwwjun41lwa) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                  |
|            | [Session 10 - 4](https://youtu.be/K-8WJJ5_XR0?si=o6OUPKMoMotRco1F) |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                  |
| Session 11 | [Session 11 - 1](https://youtu.be/t-2-OJwzlms?si=XKnhYW4bDVI8zzdU) | [Session 11 Notes](https://www.dropbox.com/scl/fi/629n3lbzhbu5hq48gu86y/PUBH614-session-11-notes-view.pdf)
: PUBH614 lectures {.striped .hover}