name: CI - Install R and Dependencies

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-r:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R environment
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends software-properties-common dirmngr

          # Add R repo and key (alternative method for better control)
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0xA5D0B5A3D5EC51D1
          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/"
          sudo apt update
          sudo apt install -y r-base

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(setdiff(c("tidyverse", "renv", "quarto"), rownames(installed.packages())), repos="https://cloud.r-project.org")'

      - name: Verify R installation
        run: R --version
