name: CI - Install R and Dependencies

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-r:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R environment
        run: |
          sudo apt update
          sudo apt install --no-install-recommends software-properties-common dirmngr

          # Add R repo and key
          sudo add-apt-repository -y ppa:c2d4u.team/c2d4u4.0+
          sudo apt update
          sudo apt install -y r-base

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(setdiff(c("tidyverse", "renv", "quarto"), rownames(installed.packages())), repos="https://cloud.r-project.org")'

      - name: Verify R installation
        run: R --version
