name: Render Quarto webR Website

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest  # Ensure consistent testing environment with Ubuntu

    permissions:
      contents: write  # Grant permission to modify contents (used for deployment)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2  # Ensure Pandoc is set up for Quarto rendering

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.6.41"  # Pin to current stable release

      - name: Verify Quarto Installation
        run: |
          quarto --version || exit 1  # Ensure Quarto is installed

      - name: Install Node.js (for webR JavaScript support)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use Node.js version for compatibility with webR

      - name: Install webR
        run: |
          npm install -g @r-wasm/webr  # Install webR for Quarto webR support

      - name: Cache Quarto Output
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/quarto
          key: ${{ runner.os }}-quarto-output-${{ hashFiles('**/*.qmd') }}
          restore-keys: |
            ${{ runner.os }}-quarto-output-

      - name: Render Quarto webR Website
        run: |
          quarto render --no-execute-daemon  # Ensure compatibility with webR
        continue-on-error: false

      - name: Debug Render Failure
        if: failure()
        run: |
          ls -la _site/ || echo "No _site directory"
          cat _site/*.log || echo "No log files found"

      - name: Deploy to GitHub Pages
        if: success() && github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          clean: true

      - name: Notify on Failure
        if: failure()
        run: |
          echo "::error:: Quarto rendering failed! Check logs in GitHub Actions."
